### Probando el registro de usuarios
POST http://localhost:3000/register
Content-Type: application/json

{
   "fullname": "samuel rojas",
   "email": "rojas10@gmail.com",
   "password": "salypimienta"
}

### Probando el login de usuario
POST http://localhost:3000/login
Content-Type: application/json

{
  // "fullname": "",
   "email": "rojas10@gmail.com",
   "password": "salypimienta"
}
### Obteniendo un profile
POST http://localhost:3000/myprofile 
Content-Type: application/json

{
   "id": "60ecd5793bd7036564d78753"
}

### Eliminando un profile
DELETE http://localhost:3000/deleteprofile
Content-Type: application/json

{
   "id": "60ecd5793bd7036564d78753"
}

### Actualizando un Profile
PUT http://localhost:3000/uptadeprofile
Content-Type:  application/json

{   
    "id": "60e8be1a8940310ca89def90",
    "fullname": "MANUEL",
    "email": "MANU@gmail.com"
}


### TASKS


### Agregando una tarea
POST http://localhost:3000/addtask
Content-Type: application/json

{
   "title": "Lavar los platos",
   "description":"con mucho jabon",
   "timelimit": "Hasta las 12pm ",
   "datelimit": "1624904420875",
   "tags":"NO MUY IMPORTANTE",
   "category": "comida",
   "count": 20
}

### Obteniendo toda las tareas
GET http://localhost:3000/alltasks

### Actualizando la tarea 
PUT http://localhost:3000/uptadetask
Content-Type: application/json

{
    "id": "60e8cf9221e0a965683c2dc1",
    "title": "Realizar el proyecto de moviles",
    "description":"Estudiar React Native",
    "timelimit": "Hasta las 12pm ",
    "datelimit": "miercoles 20",
    "tags":"MUY IMPORTANTE"
}

### Obteniendo una tarea
POST http://localhost:3000/task
Content-Type: application/json

{
    "id": "60e8cefa21013a5998ed2f23"

}

### Eliminando una tarea
DELETE http://localhost:3000/deletetask
Content-Type: application/json

{
    "id": "60e8cefa21013a5998ed2f23"
}

### Buscar tarea por el titulo
post http://localhost:3000/taskbytitle
Content-Type: application/json

{
    "title": "Cocinar sopa"

}

### Obteniendo las estadisticas
GET http://localhost:3000/taskstatistics

{
    "id":"60ec616dc0927a539c50f771",
    "count" : 20
}