### Probando el registro de usuarios
POST http://localhost:3000/register
Content-Type: application/json

{
   "fullname": "santiago rangel",
   "email": "mira@gmail.com",
   "password": "salypimienta",
   "confirmpass":"salypimienta"
}

### Probando el login de usuario
POST http://localhost:3000/login
Content-Type: application/json

{
  // "fullname": "",
   "email": "mira@gmail.com",
   "password": "salypimienta"
}
### Obteniendo un profile
POST http://localhost:3000/myprofile 
Content-Type: application/json

{
   "id": "60ef6f1a08bb9b3018c2e406"
}

### Eliminando un profile
DELETE http://localhost:3000/deleteprofile
Content-Type: application/json

{
   "id": "60ef6f1a08bb9b3018c2e406"
}

### Actualizando un Profile
PUT http://localhost:3000/uptadeprofile
Content-Type:  application/json

{   
    "id": "60ef61e394f3690c68d0751a",
    "fullname": "cesar",
    "email": "cesar@gmail.com"
}


### TASKS


### Agregando una tarea
POST http://localhost:3000/addtask
Content-Type: application/json

{
   "title": "ayudar a mi sobrino con la tarea",
   "description":"tarea de matematicas",
   "timelimit": "Hasta las 12pm ",
   "datelimit": "1624904420875",
   "tags":"NO MUY IMPORTANTE",
   "category": "comida",
   "status": "en curso"
}

### Obteniendo toda las tareas
GET http://localhost:3000/alltasks

### Actualizando la tarea 
PUT http://localhost:3000/uptadetask/60ef707a4fcef671f86dcffd
Content-Type: application/json

{
    "title": "ayudar a mi sobrino",
    "description":"tiene muchas tareas",
    "timelimit": "Hasta las 12pm ",
    "datelimit": "1624904420875",
    "tags":"MUY IMPORTANTE"
}

### Obteniendo una tarea
POST http://localhost:3000/task
Content-Type: application/json

{
    "id": "60ec616dc0927a539c50f771"

}

### Eliminando una tarea
DELETE http://localhost:3000/deletetask
Content-Type: application/json

{
    "id": "60eccb163a80404824966c77"
}

### Buscar tarea por el titulo
post http://localhost:3000/taskbytitle
Content-Type: application/json

{
    "title": "Cocinar sopa"

}

### Buscar tarea por la descripcion
post http://localhost:3000/taskbydescription
Content-Type: application/json

{
    "description": "Picar las verduras muy delgadas"

}

### Obteniendo las estadisticas
GET http://localhost:3000/taskstatistics

{
    "id":"60ec616dc0927a539c50f771",
    "count" : 20
}